name: sleeping_bear_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  provider: ^6.1.1
  intl: ^0.19.0 
  http: ^1.2.0
  shared_preferences: ^2.2.2 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 # <--- NEW

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# <--- NEW CONFIGURATION BELOW
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/sleeping_bear_logo.jpg" 
  min_sdk_android: 21